QA fixes round 2
fylein/fyle-integrations-settings-app pull request #65
Opened 2023-04-03 12:32 UTC by DhaaraniCIT

2023-04-04 12:51 UTC, ashwin1111 requested changes

2023-04-04 12:51 UTC, ashwin1111 commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.ts
> +    if (this.appName === AppName.GUSTO) {
let's do this for all the apps, doesn't make sense to do it only for gusto

2023-04-06 09:22 UTC, ashwin1111 commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.html
> +            <p *ngIf="appName !== AppName.GUSTO" class="tw-pb-10-px tw-text-faded-text-color tw-text-12-px">
why are we hiding this for gusto?

2023-04-06 09:30 UTC, DhaaraniCIT commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.html
> +            <p *ngIf="appName !== AppName.GUSTO" class="tw-pb-10-px tw-text-faded-text-color tw-text-12-px">
The design team wants to hide it

2023-04-06 09:30 UTC, ashwin1111 commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.html
> +            <p *ngIf="appName !== AppName.GUSTO" class="tw-pb-10-px tw-text-faded-text-color tw-text-12-px">
can you point me to the message link?

2023-04-06 09:30 UTC, DhaaraniCIT commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.html
> +            <p *ngIf="appName !== AppName.GUSTO" class="tw-pb-10-px tw-text-faded-text-color tw-text-12-px">
they reported it that it should be as in design, thats why

2023-04-06 09:32 UTC, DhaaraniCIT commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.html
> +            <p *ngIf="appName !== AppName.GUSTO" class="tw-pb-10-px tw-text-faded-text-color tw-text-12-px">
https://fylein.slack.com/archives/C04GGNXSEAW/p1680602711419119?thread_ts=1680514080.584629&cid=C04GGNXSEAW

2023-04-06 10:19 UTC, ashwin1111 approved these changes

2023-04-06 10:19 UTC, ashwin1111 commented on src/app/shared/components/apps/email-multi-select-field/email-multi-select-field.component.ts
> +import { AppName, ClickEvent, ToastSeverity } from 'src/app/core/models/enum/enum.model';
AppName is unused

2023-04-06 10:44 UTC, merged